version: '2'
services:
  ipfs:
    image: jlubbers08/ipfs
    networks:
     - ipfs
    dns: 
     - consul
    environment:
     - DC_NAME=ipfs
    volumes:
     - /data/
    ports:
     - 50001
     - 8080
     - 40001
    privileged: true
