version: '2'
services:
  ipfs:
    extends:
        file: base.yml
        service: ipfs
    hostname: ipfs
    container_name: ipfs
    ports:
     - "8080:8080"
     - "50003:5001"
     - "40001:4001"
    environment:
     - IPFS_BIND_IP=0.0.0.0
     - IPFS_BOOTSTRAP_RM_ALL=true
     - GATEWAY_PORT=8080
     - API_PORT=5001
    volumes:
     - ./data/:/input/

